# Generated by Django 5.0.3 on 2024-03-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=35)),
                ('fathername', models.CharField(max_length=35)),
                ('phone_number', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=60)),
                ('cooperation', models.TextField()),
                ('investment', models.TextField()),
                ('about_investor', models.TextField()),
                ('photo_investor', models.ImageField(null=True, upload_to='photos_investor/')),
                ('social_network_1', models.CharField(max_length=1000)),
                ('social_network_2', models.CharField(blank=True, default='не указано', max_length=1000)),
                ('social_network_3', models.CharField(blank=True, default='не указано', max_length=1000)),
            ],
        ),
    ]
