# Generated by Django 5.0.3 on 2024-04-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0002_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='text_offer',
            field=models.TextField(blank=True, default='', max_length=3000),
        ),
    ]
