# Generated by Django 5.0.3 on 2024-04-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=35)),
                ('fathername', models.CharField(max_length=35)),
                ('phone_number', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=60)),
                ('name_brang', models.CharField(max_length=50)),
                ('about_designer', models.TextField()),
                ('about_brand', models.TextField()),
                ('for_whom', models.TextField()),
                ('photo_logo', models.ImageField(null=True, upload_to='photos_logo/')),
                ('styles', models.TextField(max_length=2000)),
                ('nishes', models.TextField(max_length=2000)),
                ('social_network_1', models.CharField(max_length=1000)),
                ('social_network_2', models.CharField(blank=True, default='не указано', max_length=1000)),
                ('social_network_3', models.CharField(blank=True, default='не указано', max_length=1000)),
                ('investor', models.TextField(max_length=5000)),
                ('money_for_brand', models.TextField(max_length=3000)),
                ('realization', models.TextField(max_length=5000)),
                ('comment_suppliers', models.TextField(blank=True, default='', max_length=5000)),
                ('document_plan', models.FileField(null=True, upload_to='documents/')),
            ],
            options={
                'verbose_name_plural': 'Designers',
            },
        ),
    ]
